name: dxcode_storage
description: A DXCode package for securely storing sensitive data.
version: 0.0.4
# author: DXCode Team
# homepage: https://github.com/DXCode/dx_code_secure_storage
homepage: 

environment:
  sdk: ^3.8.0-149.0.dev
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  encrypt: ^5.0.3
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
