name: dxcode_storage
description: A DXCode package for securely storing sensitive data.
version: 0.1.0
# homepage: https://github.com/DXCode/dx_code_secure_storage

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ">=9.2.4 <11.0.0"
  encrypt: ^5.0.3
  crypto: ^3.0.6
  pointycastle: ^3.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
